# Generated by Django 3.0.5 on 2020-05-05 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0002_auto_20200505_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 40, 55, 983881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 40, 55, 985880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='init_deposit',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
