# Generated by Django 3.0.5 on 2020-05-05 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0003_auto_20200505_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 41, 3, 183115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 11, 41, 3, 185118, tzinfo=utc)),
        ),
    ]
