# Generated by Django 3.0.5 on 2020-05-05 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0004_auto_20200505_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
