# Generated by Django 3.0.5 on 2020-05-08 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0005_auto_20200505_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='date',
        ),
        migrations.AddField(
            model_name='operation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
