# Generated by Django 3.0.5 on 2020-05-08 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0006_auto_20200508_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='currency',
        ),
        migrations.AddField(
            model_name='operation',
            name='currency_bought',
            field=models.CharField(default='BTC', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='currency_sold',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='exchange_name',
            field=models.CharField(default='BINANCE', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and time at which the operation was closed'),
        ),
    ]
