# Generated by Django 3.0.5 on 2020-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0007_auto_20200508_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='amount',
            new_name='amount_bought',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='eventual_price',
            new_name='eventual_rate',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='is_buy',
        ),
        migrations.AddField(
            model_name='operation',
            name='buy_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='comission_percentage',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='currency_bought',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='currency_sold',
            field=models.CharField(max_length=20),
        ),
    ]
