# Generated by Django 3.0.5 on 2020-05-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0008_auto_20200509_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='comission_percentage',
            new_name='commission_percentage',
        ),
    ]
