# Generated by Django 3.0.5 on 2020-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0009_auto_20200510_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
