# Generated by Django 3.0.5 on 2020-05-24 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0010_auto_20200510_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='limit_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date and time at which the operation was closed'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='eventual_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
