# Generated by Django 3.0.5 on 2020-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0011_auto_20200524_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='buy_rate',
        ),
        migrations.AddField(
            model_name='operation',
            name='amount_sold',
            field=models.DecimalField(decimal_places=8, default=2, max_digits=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='is_open',
            field=models.BooleanField(),
        ),
    ]
