# Generated by Django 3.0.5 on 2020-05-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0013_auto_20200524_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='eventual_rate',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=9, null=True),
        ),
    ]
