# Generated by Django 3.0.5 on 2020-05-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader_journal', '0014_auto_20200524_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='limit_exceeded',
        ),
    ]
